# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2bda0b6cbe40c881d0eb1e50f2c62925dbfd466975837d07a0b1fbd6a7ca5dc03632a84416cf6b3f0ee1cceb20f27203866ce4cf00db0b9ea2004a98ac47b19a

test:
  secret_key_base: a21f6c1d59da7d647b15cac55dec7193f49c6cc5795debdacf502141833beb01fc7a4833891a1030352639162db96e091b8c61608024ce1a8627f616552f5821

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
