# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 402ee5c617503942bbff778739995c6d29383f2e61420bafd425530637064c9f23a3ad89663bad23689319871c36794cd2851f6ee6a5bfc5f323e3cbb0fdb150

test:
  secret_key_base: 4a674278a6258a31b1640b762c4a18d5605bf318fd3742a343ee07b5c58f1a48a54a6d1fdfd47fa105982d9340d067dad7ad6db3782b07762abe75ece11f5454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
